apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: veda-ingress
  annotations:
    kubernetes.io/ingress.class: azure-application-gateway
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts: [api.projectdev.in, app.projectdev.in]
      secretName: veda-tls
  rules:
    - host: api.projectdev.in
      http:
        paths:
          - path: /webhooks
            pathType: Prefix
            backend: { service: { name: edge, port: { number: 80 } } }
          - path: /
            pathType: Prefix
            backend: { service: { name: edge, port: { number: 80 } } }
    - host: app.projectdev.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: { service: { name: dashboard, port: { number: 80 } } }
